// GM Display — bindings.js
// Wires every control in gm_display.html to its handler.
//
// Generated by tools/unwire-inline.js from the inline on*= attributes the
// markup used to carry. Controls with an id are matched by it; the rest were
// given a data-act hook. Keeping this in one generated table means a control
// cannot quietly lose its handler — bind() reports anything that matches no
// element, and the regression harness asserts that list is empty.
import { cropFill, cropFit, hideTextOnPlayer, setZoomPercent, showTextOnPlayer, updateCrop, zoomBy } from './crop.js';
import { copyPreset, newPreset, setTool, syncNow, toggleLiveSync } from './fog-presets.js';
import { startImageMode, switchToMapFog } from './fog.js';
import { deleteActiveGame, moveModulePrompt, newCampaignPrompt, newGamePrompt, onCampaignSelectChange, onGameSelectChange, renameActiveGame } from './games.js';
import { openDisplay } from './init.js';
import { addArtFromVault, refreshArtVaultOptions } from './per-map-store.js';
import { nudgeCorner, resetCorner, resetProjection, rotateBy, setBg, setGridColor, setRotation, toggleGrid, toggleTestPattern, updateGridOpacity, updateGridSize, updateScale } from './projection.js';
import { remoteChangeCharacter, remoteToggleMarker } from './remote-page.js';
import { fogRedo, fogUndo, hideAll, revealAll, toggleSidebarCollapsed } from './sidebar.js';
import { addRosterTokenFromSelect, createTokenFromForm, nudgeKeyCell, nudgeKeyCellY, nudgeKeyOrigin, refreshTokenImageOptions, resetMapKey, setKeyAcross, setKeyCell, setKeyCellY, setKeyOx, setKeyOy, setKeyShape, setTokenGridColor, toggleKeyLink, toggleMarkerMode, toggleTokenGrid } from './tokens.js';
const unbound = [];
let bound = 0;

function bind(selector, event, handler) {
  const els = document.querySelectorAll(selector);
  if (!els.length) { unbound.push(selector + " (" + event + ")"); return; }
  els.forEach(el => el.addEventListener(event, (e) => handler(e, el)));
  bound++;
}

export function attachGmBindings() {
  bind('#sidebar-collapse-btn', 'click', () => { toggleSidebarCollapsed(); });
  bind('#campaign-select', 'change', (_e, el) => { onCampaignSelectChange(el.value); });
  bind('[data-act="b1"]', 'click', () => { newCampaignPrompt(); });
  bind('#game-select', 'change', (_e, el) => { onGameSelectChange(el.value); });
  bind('[data-act="b2"]', 'click', () => { newGamePrompt(); });
  bind('[data-act="b3"]', 'click', () => { renameActiveGame(); });
  bind('[data-act="b4"]', 'click', () => { moveModulePrompt(); });
  bind('[data-act="b5"]', 'click', () => { deleteActiveGame(); });
  bind('[data-act="b6"]', 'click', () => { openDisplay('map'); });
  bind('[data-act="b7"]', 'click', () => { openDisplay('show'); });
  bind('[data-act="b8"]', 'click', () => { refreshArtVaultOptions(); });
  bind('[data-act="b9"]', 'click', () => { addArtFromVault(); });
  bind('[data-act="b10"]', 'click', () => { document.getElementById('art-file-input').click(); });
  bind('[data-act="b11"]', 'click', () => { startImageMode(); });
  bind('[data-act="b12"]', 'click', () => { switchToMapFog(); });
  bind('#btn-reveal', 'click', () => { setTool('reveal'); });
  bind('#btn-hide', 'click', () => { setTool('hide'); });
  bind('[data-act="b13"]', 'click', () => { revealAll(); });
  bind('[data-act="b14"]', 'click', () => { hideAll(); });
  bind('#btn-fog-undo', 'click', () => { fogUndo(); });
  bind('#btn-fog-redo', 'click', () => { fogRedo(); });
  bind('#btn-live-sync', 'click', () => { toggleLiveSync(); });
  bind('#btn-sync-now', 'click', () => { syncNow(); });
  bind('[data-act="b15"]', 'click', () => { rotateBy(-90); });
  bind('[data-act="b16"]', 'click', () => { rotateBy(90); });
  bind('[data-act="b17"]', 'click', () => { setRotation(180); });
  bind('[data-act="b18"]', 'click', () => { setRotation(0); });
  bind('#btn-crop-fit', 'click', () => { cropFit(); });
  bind('#btn-crop-fill', 'click', () => { cropFill(); });
  bind('[data-act="b19"]', 'click', () => { zoomBy(-0.05); });
  bind('[data-act="b20"]', 'click', () => { zoomBy(0.05); });
  bind('#crop-zoom', 'input', () => { updateCrop(); });
  bind('#crop-zoom-input', 'input', (_e, el) => { setZoomPercent(el.value); });
  bind('#map-bg-color', 'input', (_e, el) => { setBg(el.value); });
  bind('[data-act="b21"]', 'click', () => { setBg('#000000'); });
  bind('[data-act="b22"]', 'click', () => { setBg('#ffffff'); });
  bind('[data-act="b23"]', 'click', () => { setBg('#222222'); });
  bind('[data-act="b24"]', 'click', () => { setBg('#888888'); });
  bind('#crop-hpos', 'input', () => { updateCrop(); });
  bind('#crop-vpos', 'input', () => { updateCrop(); });
  bind('#rotation-slider', 'input', (_e, el) => { setRotation(el.value); });
  bind('[data-act="b25"]', 'click', () => { nudgeCorner('tl','x',-1); });
  bind('[data-act="b26"]', 'click', () => { nudgeCorner('tl','y',-1); });
  bind('[data-act="b27"]', 'click', () => { nudgeCorner('tl','y',1); });
  bind('[data-act="b28"]', 'click', () => { nudgeCorner('tl','x',1); });
  bind('[data-act="b29"]', 'click', () => { resetCorner('tl'); });
  bind('[data-act="b30"]', 'click', () => { nudgeCorner('tr','x',-1); });
  bind('[data-act="b31"]', 'click', () => { nudgeCorner('tr','y',-1); });
  bind('[data-act="b32"]', 'click', () => { nudgeCorner('tr','y',1); });
  bind('[data-act="b33"]', 'click', () => { nudgeCorner('tr','x',1); });
  bind('[data-act="b34"]', 'click', () => { resetCorner('tr'); });
  bind('[data-act="b35"]', 'click', () => { nudgeCorner('bl','x',-1); });
  bind('[data-act="b36"]', 'click', () => { nudgeCorner('bl','y',-1); });
  bind('[data-act="b37"]', 'click', () => { nudgeCorner('bl','y',1); });
  bind('[data-act="b38"]', 'click', () => { nudgeCorner('bl','x',1); });
  bind('[data-act="b39"]', 'click', () => { resetCorner('bl'); });
  bind('[data-act="b40"]', 'click', () => { nudgeCorner('br','x',-1); });
  bind('[data-act="b41"]', 'click', () => { nudgeCorner('br','y',-1); });
  bind('[data-act="b42"]', 'click', () => { nudgeCorner('br','y',1); });
  bind('[data-act="b43"]', 'click', () => { nudgeCorner('br','x',1); });
  bind('[data-act="b44"]', 'click', () => { resetCorner('br'); });
  bind('#btn-test-pattern', 'click', () => { toggleTestPattern(); });
  bind('#scale-slider', 'input', (_e, el) => { updateScale(el.value); });
  bind('#btn-grid', 'click', () => { toggleGrid(); });
  bind('#grid-px-slider', 'input', (_e, el) => { updateGridSize(el.value); });
  bind('#grid-opacity-slider', 'input', (_e, el) => { updateGridOpacity(el.value); });
  bind('[data-act="b45"]', 'click', () => { setGridColor('rgba(255,255,255,__A__)'); });
  bind('[data-act="b46"]', 'click', () => { setGridColor('rgba(0,0,0,__A__)'); });
  bind('[data-act="b47"]', 'click', () => { setGridColor('rgba(0,150,255,__A__)'); });
  bind('[data-act="b48"]', 'click', () => { setGridColor('rgba(255,50,50,__A__)'); });
  bind('[data-act="b49"]', 'click', () => { resetProjection(); });
  bind('#btn-tokgrid', 'click', () => { toggleTokenGrid(); });
  bind('#tokgrid-color', 'input', () => { setTokenGridColor(); });
  bind('#tokgrid-opacity', 'input', () => { setTokenGridColor(); });
  bind('#btn-key-square', 'click', () => { setKeyShape('square'); });
  bind('#btn-key-hex', 'click', () => { setKeyShape('hex'); });
  bind('#btn-key-hexflat', 'click', () => { setKeyShape('hexflat'); });
  bind('#key-cell', 'input', (_e, el) => { setKeyCell(el.value); });
  bind('[data-act="b50"]', 'click', () => { nudgeKeyCell(-1); });
  bind('[data-act="b51"]', 'click', () => { nudgeKeyCell(-0.1); });
  bind('[data-act="b52"]', 'click', () => { nudgeKeyCell(0.1); });
  bind('[data-act="b53"]', 'click', () => { nudgeKeyCell(1); });
  bind('#key-across', 'input', (_e, el) => { setKeyAcross(el.value); });
  bind('#key-link', 'change', () => { toggleKeyLink(); });
  bind('#key-celly', 'input', (_e, el) => { setKeyCellY(el.value); });
  bind('[data-act="b54"]', 'click', () => { nudgeKeyCellY(-1); });
  bind('[data-act="b55"]', 'click', () => { nudgeKeyCellY(-0.1); });
  bind('[data-act="b56"]', 'click', () => { nudgeKeyCellY(0.1); });
  bind('[data-act="b57"]', 'click', () => { nudgeKeyCellY(1); });
  bind('#key-ox', 'input', (_e, el) => { setKeyOx(el.value); });
  bind('#key-oy', 'input', (_e, el) => { setKeyOy(el.value); });
  bind('[data-act="b58"]', 'click', () => { nudgeKeyOrigin(-1,0); });
  bind('[data-act="b59"]', 'click', () => { nudgeKeyOrigin(1,0); });
  bind('[data-act="b60"]', 'click', () => { nudgeKeyOrigin(0,-1); });
  bind('[data-act="b61"]', 'click', () => { nudgeKeyOrigin(0,1); });
  bind('[data-act="b62"]', 'click', () => { resetMapKey(); });
  bind('[data-act="b63"]', 'click', () => { refreshTokenImageOptions(); });
  bind('[data-act="b64"]', 'click', () => { createTokenFromForm(); });
  bind('[data-act="b65"]', 'click', () => { addRosterTokenFromSelect(); });
  bind('#btn-marker', 'click', () => { toggleMarkerMode(); });
  bind('[data-act="b66"]', 'click', () => { showTextOnPlayer(); });
  bind('[data-act="b67"]', 'click', () => { hideTextOnPlayer(); });
  bind('[data-act="b68"]', 'click', () => { newPreset('empty'); });
  bind('[data-act="b69"]', 'click', () => { newPreset('full'); });
  bind('[data-act="b70"]', 'click', () => { copyPreset(); });
  return unbound;
}

export function attachPlayerBindings() {
  return unbound;
}

export function attachRemoteBindings() {
  bind('#remote-change-btn', 'click', () => { remoteChangeCharacter(); });
  bind('#remote-marker-btn', 'click', () => { remoteToggleMarker(); });
  return unbound;
}

export function unboundSelectors() { return unbound.slice(); }
export function boundCount() { return bound; }
