#!/usr/bin/env node
/**
 * Replaces the inline on*= attributes in gm_display.html with explicit
 * addEventListener bindings in js/bindings.js.
 *
 * Inline handlers resolve against the global scope, which is the only reason
 * main.js still had to publish 162 names onto `window`. Once every control is
 * bound from a module, that shim can go.
 *
 * The handler expressions are kept verbatim (parsed, with `this` rewritten to
 * the element) rather than hand-rewritten, so the behaviour is carried across
 * mechanically instead of by 107 opportunities to make a typo.
 *
 * Run from the gm-display directory:  node tools/unwire-inline.js
 */
const fs = require('fs');
const path = require('path');
const acorn = require('acorn');
const walk = require('acorn-walk');

const ROOT = path.join(__dirname, '..');
const htmlPath = path.join(ROOT, 'gm_display.html');
let html = fs.readFileSync(htmlPath, 'utf8');

// ---- find every on* attribute, in document order --------------------------
const ATTR = /\son([a-z]+)="([^"]*)"/g;
const TAG = /<([a-zA-Z][\w-]*)((?:\s[^<>]*?)?)>/g;

const bindings = [];
let autoId = 0;
let out = '';
let last = 0;

for (const m of html.matchAll(TAG)) {
  const [full, tag, attrs] = m;
  if (!/\son[a-z]+="/.test(attrs)) continue;

  const idMatch = attrs.match(/\sid="([^"]+)"/);
  let selector, newAttrs = attrs;

  const handlers = [...attrs.matchAll(ATTR)];
  if (idMatch) {
    selector = '#' + idMatch[1];
  } else {
    const key = 'b' + (++autoId);
    selector = `[data-act="${key}"]`;
    newAttrs = ` data-act="${key}"` + newAttrs;
  }

  for (const h of handlers) {
    const [, event, rawExpr] = h;
    const expr = rawExpr.replace(/&quot;/g, '"').replace(/&amp;/g, '&').replace(/&#39;/g, "'");
    bindings.push({ selector, event, expr, tag });
  }
  newAttrs = newAttrs.replace(ATTR, '');

  out += html.slice(last, m.index) + `<${tag}${newAttrs}>`;
  last = m.index + full.length;
}
out += html.slice(last);
html = out;

// ---- rewrite `this` -> el, and collect the functions each handler calls ----
const called = new Set();
const lines = [];
for (const b of bindings) {
  let code = b.expr.trim();
  let ast;
  try {
    ast = acorn.parse(code, { ecmaVersion: 2022, ranges: true, allowReturnOutsideFunction: true });
  } catch (e) {
    console.error(`  ! unparseable handler on ${b.selector}: ${code}`);
    process.exitCode = 1;
    continue;
  }
  walk.simple(ast, {
    CallExpression(n) { if (n.callee.type === 'Identifier') called.add(n.callee.name); },
  });
  // replace ThisExpression nodes right-to-left
  const thises = [];
  walk.simple(ast, { ThisExpression(n) { thises.push(n); } });
  thises.sort((a, b2) => b2.range[0] - a.range[0])
        .forEach(n => { code = code.slice(0, n.range[0]) + 'el' + code.slice(n.range[1]); });
  const usesEvent = /(?<![\w$.])event(?![\w$])/.test(code);
  const params = usesEvent ? '(event, el)' : (thises.length ? '(_e, el)' : '()');
  lines.push({ ...b, code: code.replace(/;\s*$/, ''), params });
}

// ---- work out where each called function lives ----------------------------
const JS = path.join(ROOT, 'js');
const owner = {};
for (const f of fs.readdirSync(JS)) {
  if (!f.endsWith('.js') || f === 'main.js' || f === 'bindings.js') continue;
  const ast = acorn.parse(fs.readFileSync(path.join(JS, f), 'utf8'),
                          { ecmaVersion: 2022, sourceType: 'module' });
  for (const n of ast.body) {
    if (n.type !== 'ExportNamedDeclaration' || !n.declaration) continue;
    const d = n.declaration;
    (d.id ? [d.id.name] : (d.declarations || []).map(x => x.id.name)).forEach(x => { owner[x] = f; });
  }
}
const missing = [...called].filter(n => !owner[n]);
if (missing.length) {
  console.error('  ! no module exports:', missing.join(', '));
  process.exitCode = 1;
}

const byModule = {};
for (const n of called) if (owner[n]) (byModule[owner[n]] = byModule[owner[n]] || []).push(n);

// ---- emit js/bindings.js --------------------------------------------------
const src = [];
src.push('// GM Display — bindings.js');
src.push('// Wires every control in gm_display.html to its handler.');
src.push('//');
src.push('// Generated by tools/unwire-inline.js from the inline on*= attributes the');
src.push('// markup used to carry. Controls with an id are matched by it; the rest were');
src.push('// given a data-act hook. Keeping this in one generated table means a control');
src.push('// cannot quietly lose its handler — bind() reports anything that matches no');
src.push('// element, and the regression harness asserts that list is empty.');
src.push('');
for (const mod of Object.keys(byModule).sort()) {
  src.push(`import { ${byModule[mod].sort().join(', ')} } from './${mod}';`);
}
src.push('');
src.push('const unbound = [];');
src.push('');
src.push('function bind(selector, event, handler) {');
src.push('  const els = document.querySelectorAll(selector);');
src.push('  if (!els.length) { unbound.push(selector + " (" + event + ")"); return; }');
src.push('  els.forEach(el => el.addEventListener(event, (e) => handler(e, el)));');
src.push('}');
src.push('');
src.push('export function attachBindings() {');
for (const l of lines) {
  src.push(`  bind('${l.selector}', '${l.event}', ${l.params} => { ${l.code}; });`);
}
src.push('  if (unbound.length) console.warn("[bindings] no element for:", unbound);');
src.push('  return unbound;');
src.push('}');
src.push('');
src.push('export function unboundSelectors() { return unbound.slice(); }');
fs.writeFileSync(path.join(JS, 'bindings.js'), src.join('\n') + '\n');
fs.writeFileSync(htmlPath, html);

console.log(`handlers moved      : ${lines.length}`);
console.log(`elements given a hook: ${autoId}`);
console.log(`functions imported  : ${called.size} from ${Object.keys(byModule).length} modules`);
console.log(`inline attrs left   : ${(html.match(/\son[a-z]+="/g) || []).length}`);
